routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');

Auth::routes(['register' => false]);

Route::prefix('admin')->name('adm.')->group(function () {
    Route::get('/', 'AdminController@index')->name('panel');

    Route::prefix('blog')->name('blog.')->group(function() {
        Route::get('', 'BlogController@index')->name('index');
        Route::get('create', 'BlogController@create')->name('create');
        Route::post('create', 'BlogController@store')->name('store');
        Route::get('{id}', 'BlogController@show')->name('show');
        Route::post('{id}', 'BlogController@update')->name('update');
        Route::post('{id}/destroy', 'BlogController@destroy')->name('destroy'); 
    });

    Route::prefix('construction')->name('construction.')->group(function() {
        Route::get('', 'ConstructionController@index')->name('index');
        Route::get('create', 'ConstructionController@create')->name('create');
        Route::post('create', 'ConstructionController@store')->name('store');
        Route::get('{id}', 'ConstructionController@show')->name('show');
        Route::post('{id}', 'ConstructionController@update')->name('update');
        Route::post('{id}/destroy', 'ConstructionController@destroy')->name('destroy'); 
    });

    Route::prefix('category')->name('category.')->group(function() {
        Route::get('', 'CategoryController@index')->name('index');
        Route::get('create', 'CategoryController@create')->name('create');
        Route::post('create', 'CategoryController@store')->name('store');
        Route::get('{id}', 'CategoryController@show')->name('show');
        Route::post('{id}', 'CategoryController@update')->name('update');
        Route::post('{id}/destroy', 'CategoryController@destroy')->name('destroy'); 
    });
});

app/Http/Controllers/BlogController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Post;
use Illuminate\Http\Request;

class BlogController extends Controller
{
    protected $blog;

    public function __construct(Post $post)
    {
        $this->middleware('auth');
        $this->blog = $post;
    }

    public function index()
    {
        $data = $this->blog->orderBy('id', 'desc')->paginate();

        return view('admin.blog.index', compact('data'));
    }

    public function create()
    {
        $categories = Category::pluck('name', 'id')->toArray();
        
        return view('admin.blog.create', compact('categories'));
    }

    public function store(Request $request)
    {
        $input = $request->all();
        $imageName = time().'.'.$input['img']->extension();
        $input['img']->move(public_path('storage/posts'), $imageName);

        $input['img'] = $imageName;
        $input['slug'] = \Str::slug($input['title'], '-');
        $this->blog->create($input);

        toastr()->success('Registro Salvo');

        return redirect()->route('adm.blog.index');
    }

    public function show($id)
    {
        $data = $this->blog->find($id);
        $categories = Category::pluck('name', 'id')->toArray();

        return view('admin.blog.edit', compact('data', 'categories'));
    }

    public function update($id, Request $request)
    {
        $input = $request->all();
        if (isset($input['img'])) {
            $imageName = time().'.'.$input['img']->extension();
            $input['img']->move(public_path('storage/posts'), $imageName);

            $input['img'] = $imageName;
        } else {
            unset($input['img']);
        }
        
        $this->blog->find($id)->update($input);

        toastr()->success('Registro Atualizado');

        return redirect()->route('adm.blog.index');
    }

    public function destroy($id)
    {
        $this->blog->find($id)->delete();

        toastr()->success('Registro Apagado');

        return redirect()->route('adm.blog.index');
    }
}

resources/views/admin/blog/_form.blade.php
<div class="col-sm-12 col-md-4">
  <div class="form-group mb-4">
    {!! Form::label('title', 'Título', ['class' => '']) !!}
    {!! Form::text('title', old('title'), ['class' => 'form-control required']) !!}
    @if($errors->has('title'))
      <span class="text-danger">{{ $errors->first('title') }}</span>
    @endif
  </div>
</div>

<div class="col-sm-12 col-md-4">
  <div class="form-group mb-4">
    {!! Form::label('category', 'Categoria', ['class' => '']) !!}
    {!! Form::select('category_id', $categories, null, ['class' => 'form-control required ']) !!}
    @if($errors->has('category'))
      <span class="text-danger">{{ $errors->first('category') }}</span>
    @endif
  </div>
</div>

<div class="col-sm-12 col-md-4">
  <div class="form-group mb-4">
    {!! Form::label('img', 'Imagem', ['class' => '']) !!}<br>
    {!! Form::file('img', old('img'), ['class' => 'form-control']) !!}
  </div>
</div>

<div class="col-sm-12 col-md-12">
  <div class="form-group mb-4">
    {!! Form::label('text', 'Texto', ['class' => '']) !!}
    {!! Form::textarea('text', old('text'), ['class' => 'form-control ckeditor required']) !!}
  </div>
</div>


@section('scripts')
  <script src="http://vip.ufcode.com.br/ckeditor/ckeditor.js"></script>
@endsection

resources/views/admin/blog/create.blade.php
@extends('admin.layouts.default')

@section('content')

{!! Form::open(['method' => 'POST', 'novalidate', 'role' => 'form', 'class' => 'form', 'route' => 'adm.blog.store', 'files' => true]) !!}
<section class="section">
  <div class="section-header mb-0">
    <h1>Novo Post</h1>
    <div class="section-header-button mr-2">
    </div>
  </div>

  <div class="section-options">
    <div class="text-right mb-2">
      
    </div>
  </div>

  <div class="clearfix"></div>

  <div class="section-body">
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-header -warning">
            <h4>
              <i class="fas fa-info-circle lga"></i>
              Dados pessoais
            </h4>
          </div>
          <div class="card-body">
            <div class="row">
              @include('admin.blog._form')

              <a href="{{ route('adm.blog.index') }}" class="btn btn-danger btn-lg btn-icon mr-1" title="Voltar"><i class="fas fa-angle-left"></i> Voltar</a>
              <button type="submit" class="btn btn-icon icon-left btn-success btn-lg"><i class="fas fa-check"></i> Salvar</button>
            </div>
          </div>

        </div>
      </div>
  </div>
</section>
{!! Form::close() !!}

@endsection

resources/views/admin/blog/edit.blade.php
@extends('admin.layouts.default')

@section('content')

{!! Form::model($data, ['method' => 'POST', 'novalidate', 'role' => 'form', 'class' => 'form', 'route' => ['adm.blog.update', $data->id], 'files' => true]) !!}
<section class="section">
  <div class="section-header mb-0">
    <h1>Editar Post</h1>
    <div class="section-header-button mr-2">
    </div>
  </div>

  <div class="section-options">
    <div class="text-right mb-2">
      
    </div>
  </div>

  <div class="clearfix"></div>

  <div class="section-body">
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-header -warning">
            <h4>
              <i class="fas fa-info-circle lga"></i>
              Dados pessoais
            </h4>
          </div>
          <div class="card-body">
            <div class="row">
              @include('admin.blog._form')

              <a href="{{ route('adm.blog.index') }}" class="btn btn-danger btn-lg btn-icon mr-1" title="Voltar"><i class="fas fa-angle-left"></i> Voltar</a>
              <button type="submit" class="btn btn-icon icon-left btn-success btn-lg"><i class="fas fa-check"></i> Salvar</button>
            </div>
          </div>

        </div>
      </div>
  </div>
</section>
{!! Form::close() !!}

@endsection

resources/views/admin/blog/index.blade.php
@extends('admin.layouts.default')

@section('content')

<section class="section">
  <div class="section-header">
    <h1>Posts</h1>
      <div class="section-header-button mr-2">
        <a href="{{ route('adm.blog.create') }}" class="btn btn-success btn-icon btn-lg btn-success" title="Adicionar"> <i class="fas fa-plus"></i> Adicionar</a>
      </div>
  </div>

  <div class="section-body">
    <div class="row mt-4">
      <div class="col-12">
        <div class="card">
          <div class="card-header">
            <h4>
              <i class="far fa-user lga"></i>
              Listagem de Posts <br>
              <small>{{ $data->total() }} resultados.</small>
            </h4>
          </div>
          <div class="card-body -table">
            <div class="table-responsive">
              <table class="table table-striped">
                <tbody>
                  <tr>
                    <th>#</th>
                    <th>Título</th>
                    <th>Categoria</th>
                    <th>Ações</th>
                  </tr>
                  @foreach($data as $d)
                    <tr>
                      <td>{{ $d->id }}</td>
                      <td>{{ $d->title }}</td>
                      <td>{{ $d->category_name }}</td>
                      {!! Form::open(['route' => ['adm.blog.destroy', $d->id]]) !!}
                      <td class="no-wrap">
                        <a href="{{ route('adm.blog.show', $d->id) }}" class="btn btn-success">Editar</a> | 
                        <button type="submit" class="btn btn-danger" onclick="return confirm('Essa ação não pode ser desfeita!')">Apagar</button>
                      </td>
                      {!! Form::close() !!}
                    </tr>
                  @endforeach
                </tbody>
              </table>
            </div>
          </div>
          <div class="card-footer">
            <div class="float-right">
              <nav>
                {!! $data->render() !!}
              </nav>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
@endsection